# Generated by Django 6.0.5 on 2026-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='city',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='recipient',
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التوصيل'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغى')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
